# Generated by Django 5.0.1 on 2024-02-04 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_aluno', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
