# Generated by Django 5.0.1 on 2024-02-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aluno', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Idade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
